### ISSUE TITLE
Guide failed with error 

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-microprofile-jwt#74]
Reported by Michael T. is following open liberty guide for MP-JWT, and got this error:

Exception thrown by application class 'javax.faces.webapp.FacesServlet.service:220'
javax.servlet.ServletException: View "/login.jsf" could not be restored.
at javax.faces.webapp.FacesServlet.service(FacesServlet.java:220)
at [internal classes]
Caused by: javax.faces.application.ViewExpiredException: View "/login.jsf" could not be restored.
at org.apache.myfaces.lifecycle.RestoreViewExecutor.execute(RestoreViewExecutor.java:181)
... 1 more

**Comment by yeekangc** [comment]
May be related to #37?

**Comment by proubatsis** [comment]
PR Merged.
