### ISSUE TITLE
Exception thrown when trying to login as user

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/guide-microprofile-jwt#83]
Under the "Getting Started" portion of the guide, once the server starts and I try to login in as:
Username: bob
Password: bobpwd 

I receive the following exception:

Exception thrown by application class 'javax.faces.webapp.FacesServlet.service:220'
javax.servlet.ServletException: View "/login.jsf" could not be restored.
at javax.faces.webapp.FacesServlet.service(FacesServlet.java:220)
at [internal classes]
at io.openliberty.guides.ui.filters.NoCacheFilter.doFilter(NoCacheFilter.java:23)
at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
at [internal classes]
Caused by: javax.faces.application.ViewExpiredException: View "/login.jsf" could not be restored.
at org.apache.myfaces.lifecycle.RestoreViewExecutor.execute(RestoreViewExecutor.java:181)
... 4 more

This exception is raised when I try to login as users "alice" and "carl" as well.  
Browser: Google Chrome
Platform: MacOS 

When I tried again on a clean Firefox browser I was able to login. Additionally, when I cleared my Google Chrome browser cache I was able to login.

**Comment by yeekangc** [comment]
@proubatsis @gkwan-ibm

**Comment by gkwan-ibm** [comment]
It should be caused by after ran the mpMetrics guide. The authentication was cached. Yes, the workaround is to clean up the browser cached. To address the root, need to find out how to clean the cached or log out in the mpMetrics guide.
